//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aula
    {
        public aula()
        {
            this.grupo = new HashSet<grupo>();
        }
    
        public int id { get; set; }
        public Nullable<int> plazas { get; set; }
        public string nombre { get; set; }
        public string nro_aula { get; set; }
        public string ubicacion { get; set; }
    
        public virtual ICollection<grupo> grupo { get; set; }
    }
}
