//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrera
    {
        public carrera()
        {
            this.curso = new HashSet<curso>();
            this.matricula = new HashSet<matricula>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipocarrera { get; set; }
        public Nullable<int> total_creditos { get; set; }
    
        public virtual tipocarrera tipocarrera { get; set; }
        public virtual ICollection<curso> curso { get; set; }
        public virtual ICollection<matricula> matricula { get; set; }
    }
}
