//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cursosEntities : DbContext
    {
        public cursosEntities()
            : base("name=cursosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aula> aula { get; set; }
        public DbSet<carrera> carrera { get; set; }
        public DbSet<curso> curso { get; set; }
        public DbSet<estudiante> estudiante { get; set; }
        public DbSet<grupo> grupo { get; set; }
        public DbSet<inscripcion> inscripcion { get; set; }
        public DbSet<matricula> matricula { get; set; }
        public DbSet<nota> nota { get; set; }
        public DbSet<pago> pago { get; set; }
        public DbSet<profesor> profesor { get; set; }
        public DbSet<tipocarrera> tipocarrera { get; set; }
        public DbSet<detalle_eng> detalle_eng { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
