//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_eng
    {
        public int id_grupo { get; set; }
        public int id_estudiante { get; set; }
        public int id_nota { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual nota nota { get; set; }
    }
}
