//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        public string horario { get; set; }
        public int id { get; set; }
        public Nullable<int> id_matricula { get; set; }
        public Nullable<int> id_pago { get; set; }
        public Nullable<int> id_alumno { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual matricula matricula { get; set; }
        public virtual pago pago { get; set; }
    }
}
