//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public nota()
        {
            this.detalle_eng = new HashSet<detalle_eng>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> puntaje { get; set; }
    
        public virtual ICollection<detalle_eng> detalle_eng { get; set; }
    }
}
