//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public pago()
        {
            this.inscripcion = new HashSet<inscripcion>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual ICollection<inscripcion> inscripcion { get; set; }
    }
}
