//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        public profesor()
        {
            this.grupo = new HashSet<grupo>();
        }
    
        public int id { get; set; }
        public string ci { get; set; }
        public string nombre { get; set; }
        public string titulo { get; set; }
        public string especialidad { get; set; }
    
        public virtual ICollection<grupo> grupo { get; set; }
    }
}
